//! POSIX word splitting, ported from Python's `shlex`.
//!
//! `runners.py` splits `game.arguments` with `shlex.split(...)` in four places
//! (406, 496, 509, 1269) and `installers.py` does the same for its own argument
//! field, so the behaviour of one user-visible field — the launch-arguments box
//! in the game form — is defined here.
//!
//! # Why this is hand-written rather than a crate
//!
//! `docs/migration/architecture.md` §6 leaves the choice open ("`shell-words`
//! crate — or hand-rolled splitter — decide at implementation"), so the decision
//! and its reasoning are recorded here rather than left to be re-derived.
//!
//! The crate was the obvious candidate and is a good one, but it cannot cover
//! the second caller: `parse_env_block` drives `shlex.shlex` directly with
//! `whitespace_split=True`, `commenters=""` and `escape=""` (`runners.py:1004`),
//! which is a *different configuration* of the same scanner — no escapes, no
//! comments, quotes still grouped. `shell-words` exposes only the `split`
//! configuration. So the choice was "a crate for `split` plus a hand-written
//! scanner for `parse_env_block`" or "one scanner with configuration", and the
//! latter is less code and one behaviour to keep right instead of two.
//!
//! The dependency argument points the same way: `crates/core/Cargo.toml` keeps
//! its dependency set deliberately small so `cargo test -p gamehandler-core`
//! stays instant, headless and offline, and this is ~80 lines.
//!
//! The risk of hand-writing it is that it drifts from `shlex`, which is exactly
//! the class of bug the oracle fixtures exist to catch — so the splitter is
//! pinned against the real module in
//! `docs/migration/oracle/fixtures/shell_split.in.json`, generated by
//! `run_runners_vectors.py` running CPython's `shlex`, and replayed by
//! `oracle_tests::the_hand_written_splitter_matches_pythons_shlex`. The corpus is
//! adversarial (unbalanced quotes, trailing backslashes, empty tokens, adjacent
//! quoting) rather than representative, per the lesson of F-H.
//!
//! # The two traps
//!
//! 1. **Whitespace is exactly `" \t\r\n"`, not [`char::is_whitespace`].**
//!    Python's `shlex.whitespace` defaults to that literal four-character
//!    string, and it is *not* the Unicode notion — `shlex.split("\x0b")` returns
//!    `['\x0b']`, one token of vertical tab, because `\x0b` is not in the set.
//!    Reaching for the convenient Rust predicate here silently changes which
//!    arguments are separate.
//! 2. **An empty token is a token.** `shlex.split("a '' b")` is `['a', '', 'b']`
//!    — three elements, the middle one empty — because entering a quote starts a
//!    token even when it contributes no characters. Splitting on runs of
//!    whitespace and discarding empties gives `['a', 'b']` and hands the game a
//!    different argv.

use std::fmt;

/// Why a string could not be split into words.
///
/// The two variants are Python's two `ValueError` messages, and the port keeps
/// them distinct for the same reason Python does: the message is what a user
/// sees in the launch-failure toast, and "No closing quotation" tells them to
/// look for an unbalanced quote while "No escaped character" tells them the
/// string ends in a backslash.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellError {
    /// Python: `ValueError: No closing quotation`.
    NoClosingQuotation,
    /// Python: `ValueError: No escaped character`.
    NoEscapedCharacter,
}

impl fmt::Display for ShellError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Byte-identical to the CPython messages, so a surfaced error reads the
        // same in both implementations.
        match self {
            ShellError::NoClosingQuotation => f.write_str("No closing quotation"),
            ShellError::NoEscapedCharacter => f.write_str("No escaped character"),
        }
    }
}

impl std::error::Error for ShellError {}

/// Whether `c` is in Python's default `shlex.whitespace`.
///
/// Deliberately not [`char::is_whitespace`] — see the module note's trap 1.
#[inline]
fn is_shlex_whitespace(c: char) -> bool {
    matches!(c, ' ' | '\t' | '\r' | '\n')
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Quote {
    None,
    Single,
    Double,
}

/// Split `text` into words the way `shlex.split(text)` does.
///
/// `posix=True` (the default), `comments=False` (the default), so `#` starts no
/// comment: `shlex.split("a # b")` is `['a', '#', 'b']`.
pub fn split_posix(text: &str) -> Result<Vec<String>, ShellError> {
    let mut words = Vec::new();
    let mut token = String::new();
    // Python's shlex is a state machine whose *token* state is distinct from its
    // whitespace state; a quote moves it into the token state even when it
    // appends nothing, which is what keeps `''` as a word. `started` is that
    // token state.
    let mut started = false;
    let mut quote = Quote::None;
    let mut chars = text.chars().peekable();

    while let Some(c) = chars.next() {
        match quote {
            // Single quotes are literal to the end: **no escapes at all**, so
            // `'a\'` is the two characters `a\`. Verified against CPython.
            Quote::Single => {
                if c == '\'' {
                    quote = Quote::None;
                } else {
                    token.push(c);
                }
            }
            Quote::Double => {
                if c == '"' {
                    quote = Quote::None;
                } else if c == '\\' {
                    match chars.next() {
                        // A backslash with nothing after it is an error even
                        // inside double quotes: `shlex.split("\"a\\")` raises
                        // "No escaped character", not "No closing quotation".
                        None => return Err(ShellError::NoEscapedCharacter),
                        // Inside double quotes only these two collapse.
                        // `"a\nb"` keeps the backslash, because `n` is not one
                        // of the escaped quotes — the POSIX shell would drop it.
                        Some(next) if next == '"' || next == '\\' => token.push(next),
                        Some(next) => {
                            token.push('\\');
                            token.push(next);
                        }
                    }
                } else {
                    token.push(c);
                }
            }
            Quote::None => {
                if c == '\\' {
                    match chars.next() {
                        None => return Err(ShellError::NoEscapedCharacter),
                        // Outside quotes a backslash escapes *anything*:
                        // `a\ b` is one word, `a\$b` is `a$b`.
                        Some(next) => {
                            token.push(next);
                            started = true;
                        }
                    }
                } else if c == '\'' {
                    quote = Quote::Single;
                    started = true;
                } else if c == '"' {
                    quote = Quote::Double;
                    started = true;
                } else if is_shlex_whitespace(c) {
                    if started {
                        words.push(std::mem::take(&mut token));
                        started = false;
                    }
                } else {
                    token.push(c);
                    started = true;
                }
            }
        }
    }

    // An unterminated quote is reported after the scan, so it cannot mask a
    // trailing-escape error found earlier — matching CPython's precedence.
    if quote != Quote::None {
        return Err(ShellError::NoClosingQuotation);
    }
    if started {
        words.push(token);
    }
    Ok(words)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn split(text: &str) -> Vec<String> {
        split_posix(text).expect("should split")
    }

    #[test]
    fn ordinary_arguments_split_on_whitespace() {
        assert_eq!(
            split("-fullscreen -dx11"),
            ["-fullscreen".to_string(), "-dx11".to_string()]
        );
        assert_eq!(split(" \t-x\r\n-y "), ["-x".to_string(), "-y".to_string()]);
    }

    #[test]
    fn quotes_group_and_are_removed() {
        assert_eq!(
            split("a 'b c' d"),
            ["a".to_string(), "b c".to_string(), "d".to_string()]
        );
        assert_eq!(split("\"a b\""), ["a b".to_string()]);
        assert_eq!(split("'a b'"), ["a b".to_string()]);
    }

    #[test]
    fn an_empty_quoted_word_is_a_word() {
        // Trap 2 in the module note. A splitter that discards empty tokens
        // passes every other case in this file and fails here.
        assert_eq!(split("''"), [""]);
        assert_eq!(split("\"\""), [""]);
        assert_eq!(split("-x ''"), ["-x".to_string(), String::new()]);
        assert_eq!(
            split("a '' b"),
            ["a".to_string(), String::new(), "b".to_string()]
        );
        assert_eq!(split("''  ''"), ["".to_string(), "".to_string()]);
        // A quote contributes nothing to `-b''` but is still part of the word.
        assert_eq!(split("-b''"), ["-b".to_string()]);
    }

    #[test]
    fn vertical_tab_and_form_feed_are_not_whitespace() {
        // Trap 1. `char::is_whitespace('\x0b')` is true and shlex's set says
        // otherwise, so this fails loudly if someone swaps the predicate.
        assert_eq!(split("\x0b"), ["\x0b".to_string()]);
        assert_eq!(split("a\x0cb"), ["a\x0cb".to_string()]);
    }

    #[test]
    fn adjacent_quoting_concatenates_into_one_word() {
        assert_eq!(split("a\"b\"c"), ["abc".to_string()]);
        assert_eq!(split("'a'\"b\""), ["ab".to_string()]);
        assert_eq!(split("\"a b\"c d"), ["a bc".to_string(), "d".to_string()]);
    }

    #[test]
    fn a_hash_is_not_a_comment() {
        assert_eq!(split("a#b"), ["a#b".to_string()]);
        assert_eq!(
            split("a # b"),
            ["a".to_string(), "#".to_string(), "b".to_string()]
        );
    }

    #[test]
    fn escapes_outside_quotes_remove_the_backslash() {
        assert_eq!(split("a\\ b"), ["a b".to_string()]);
        assert_eq!(split("a\\$b"), ["a$b".to_string()]);
        assert_eq!(split("-DNAME=\\'v\\'"), ["-DNAME='v'".to_string()]);
        assert_eq!(split("\\\\"), ["\\".to_string()]);
    }

    #[test]
    fn single_quotes_do_not_escape() {
        // The whole point of single quotes, and the case a scanner that treats
        // `\` uniformly gets wrong.
        assert_eq!(split("'a\\b'"), ["a\\b".to_string()]);
        assert_eq!(split("'\\'"), ["\\".to_string()]);
        assert_eq!(split("'a\\$'"), ["a\\$".to_string()]);
    }

    #[test]
    fn double_quotes_escape_only_the_quote_and_the_backslash() {
        assert_eq!(split("\"a\\\\b\""), ["a\\b".to_string()]);
        assert_eq!(split("\"a\\\"b\""), ["a\"b".to_string()]);
        // Not a shell: `\$` inside double quotes keeps its backslash.
        assert_eq!(split("\"a\\$b\""), ["a\\$b".to_string()]);
        assert_eq!(split("\"a\\nb\""), ["a\\nb".to_string()]);
    }

    #[test]
    fn an_unterminated_quote_is_an_error() {
        for text in ["'unterminated", "\"unterminated", "'a\\", "a'", "a\"b"] {
            assert_eq!(
                split_posix(text),
                Err(ShellError::NoClosingQuotation),
                "for {text:?}"
            );
        }
    }

    #[test]
    fn a_trailing_backslash_is_an_error() {
        for text in ["\\", "a\\", "x y\\"] {
            assert_eq!(
                split_posix(text),
                Err(ShellError::NoEscapedCharacter),
                "for {text:?}"
            );
        }
        // Inside double quotes a trailing backslash is the *escape* error, not
        // the quotation one, even though the quote is also unterminated.
        assert_eq!(split_posix("\"a\\"), Err(ShellError::NoEscapedCharacter));
    }

    #[test]
    fn an_escaped_quote_does_not_close_a_double_quoted_word() {
        // `"a\"` collapses the backslash-quote and is then unterminated; a
        // scanner that closes on the escaped quote returns `['a\\']` instead.
        assert_eq!(split_posix("\"a\\\""), Err(ShellError::NoClosingQuotation));
    }

    #[test]
    fn empty_and_whitespace_only_input_yield_no_words() {
        assert!(split("").is_empty());
        assert!(split("   ").is_empty());
        assert!(split("\r\n").is_empty());
    }
}
