sources = [
  '__init__.py',
  '__main__.py',
  'main.py',
  'window.py',
  'models.py',
  'config.py',
  'settings.py',
  'covers.py',
  'credits.py',
  'credits_page.py',
  'plugins.py',
  'runners.py',
  'add_game_dialog.py',
  'runners_dialog.py',
  'plugins_page.py',
  'settings_page.py',
  'installers.py',
  'installers_page.py',
  'style.css',
]

py.install_sources(sources, subdir: 'gamehandler')
